---
title:               Jack's Blog
tagline:             ''
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Jack Dempsey
twitter:             jackdempsey
github:              jackdempsey
email:               jack.dempsey@gmail..com
google_analytics_id: UA-23991123-1
